version: '3.9'

services:
    postgres:
      container_name: db
      image: 'postgres:15.1'
      hostname: postgres
      platform: linux/x86_64
      restart: always
      environment:
        - POSTGRES_PORT=5432
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=db
      volumes:
        - postgres:/var/lib/postgresql/data
      ports:
        - '5432:5432'
      expose:
        - 5432
      healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres"]
        timeout: 10s
        retries: 5

volumes:
  postgres:
