version: '3.9'

services:
    db:
      container_name: db
      image: postgres:14.1-alpine
      ports:
        - '5432:5432'
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      restart: always
      volumes:
        - ./db:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres"]
        timeout: 10s
        retries: 5
      expose:
        - 5432
